version: "3.3"
services:
  react-app:
    build: .
    volumes:
      - .:/app  # Sync local project files to container
      - /app/node_modules  # Prevents overwriting node_modules
    ports:
      - "5173:5173"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - VITE_HMR_PORT=5173  # Ensure hot reload works
    command: ["yarn", "dev", "--host"]
